### ISSUE TITLE
Upate: HmIP-eTRV-2 / HmIP-Froll

### ISSUE THREAD

**Issue by WebWolf1973** [Gerti1972/homehub#1]
Hallo, hier mein kleiner Beitrag.
[homehub.zip](https://github.com/Gerti1972/homehub/files/4604912/homehub.zip)

Gruß Patrick

**Comment by Gerti1972** [comment]
Hi!

 

Erstmal Danke.

Der eTRV-2 fehlte wohl nur in script.js, als Gerät gab es den schon.

Du hast da in der ersten Zeile „0,1“ geschrieben, was irgendwie in meinen Augen keinen Sinn macht.

Im Kanal 0 (daher eigentlich auch nur „0“) steht der Wert zum Batteriestand.

 

Beim FROLL musst Du den Status aus Kanal 3 auslesen, wie auch beim BROLL, da nur der Kanal 3 die korrekte Behanghöhe beinhaltet.

 

Ich habe im Forum mal ein Update mit den neuen Geräten hochgeladen.


Gruß,

Gerti

 

Von: WebWolf1973 <notifications@github.com> 
Gesendet: Sonntag, 10. Mai 2020 01:59
An: Gerti1972/homehub <homehub@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Gerti1972/homehub] Upate: HmIP-eTRV-2 / HmIP-Froll (#1)

 

Hallo, hier mein kleiner Beitrag.
homehub.zip <https://github.com/Gerti1972/homehub/files/4604912/homehub.zip> 

Gruß Patrick

**Comment by WebWolf1973** [comment]
Hallo Gerti,

der Batteriezustand steht im Kanal 0 und die Temperatur bzw. Profile im Kanal 1, habe es bei mir getestet.

Froll teste ich nochmal meine aber Kanal 4?ist richtig.

Bekommst ein Rückmeldung heute Abend.

Mit freundlichen Grüßen

Patrick Lehnhard

Moerserstraße 259a
47228 Duisburg (Rheinhausen)
Phone: +49 2065 9271726
Mobil: +49 175 4451026
E-Mail patrick@lehnhard.com

Überlegen Sie bitte, ob Sie diese Nachricht wirklich ausdrucken müssen / Before printing this email, think if it is necessary to do it. Think Green.
Am 11. Mai 2020, 10:42 +0200 schrieb Gerti1972 <notifications@github.com>:

**Comment by Gerti1972** [comment]
Richtig, in Kanal 0 ist der Batteriezustand, der über den Kopf in der e-TRV-2 Datei eingelesen wird.
Die restlichen Datenpunkt aus Kanal 1 werden über den normalen Weg (durch Angabe des Aktors mit Kanal in der custom.json) ausgelesen. Der Zusatz mit Kanal 0 ist bei einigen HmIP-Komponenten notwendig, da Informationen in Kanal 0 stehen. Bei klassischen Homematic Komponenten gab es diese Aufteilung auf die Kanäle nicht.

Beim FROLL steuerst Du Kanal 4 (daher auch diesen in der custom.json eintragen.
Den Status bekommst Du aber aus Kanal 3, daher muss dieser für die Anzeige verwendet werden.
Du kannst mal den Rollladen mit der Wippe nach oben fahren und im Lauf die Fahrt stoppen.
In Kanal 4 steht dann 100%, in Kanal 3 die wirkliche Behanghöhe.
Ist bei Schaltaktoren theoretisch genauso, da die aber nur 0 und 1 kennen, kann man da ruhig den Kanal 4 auch anzeigen.

**Comment by WebWolf1973** [comment]
Habe mir mit deine Bemerkungen das Skript nochmal angeschaut.

Du hast Recht und ich was gelernt.

PHP ist nicht das Problem, aber bei Homematic lerne ich immer noch dazu.

Danke für deine Arbeit.

 

Gruß

Patrick

 

 

Von: Gerti1972 <notifications@github.com> 
Gesendet: Montag, 11. Mai 2020 12:47
An: Gerti1972/homehub <homehub@noreply.github.com>
Cc: WebWolf1973 <patrick@lehnhard.com>; Author <author@noreply.github.com>
Betreff: Re: [Gerti1972/homehub] Upate: HmIP-eTRV-2 / HmIP-Froll (#1)

 

Richtig, in Kanal 0 ist der Batteriezustand, der über den Kopf in der e-TRV-2 Datei eingelesen wird.
Die restlichen Datenpunkt aus Kanal 1 werden über den normalen Weg (durch Angabe des Aktors mit Kanal in der custom.json) ausgelesen. Der Zusatz mit Kanal 0 ist bei einigen HmIP-Komponenten notwendig, da Informationen in Kanal 0 stehen. Bei klassischen Homematic Komponenten gab es diese Aufteilung auf die Kanäle nicht.

Beim FROLL steuerst Du Kanal 4 (daher auch diesen in der custom.json eintragen.
Den Status bekommst Du aber aus Kanal 3, daher muss dieser für die Anzeige verwendet werden.
Du kannst mal den Rollladen mit der Wippe nach oben fahren und im Lauf die Fahrt stoppen.
In Kanal 4 steht dann 100%, in Kanal 3 die wirkliche Behanghöhe.
Ist bei Schaltaktoren theoretisch genauso, da die aber nur 0 und 1 kennen, kann man da ruhig den Kanal 4 auch anzeigen.
